### ISSUE TITLE
Pan and rotation handles out of view

### ISSUE THREAD

**Issue by brenthuisman** [arbor-sim/gui#10]
Some morphologies open up with a viewport very much off centre. When that is the case, the handles for rotation and panning are not in the viewport and thus not usable.

Proposal: always places the handles in the center of the viewport.

Alternatively, center morphs that apparently are not centered (`stellate.asc` is the file in question).

**Comment by thorstenhater** [comment]
I'll have to take a look, but I thought we translate to root. Maybe something changed in Arbor's loader, since I am sure stellate worked. Here's an easy fix: Define a locset `(root)`, right-click view and choose 'snap' to the root.

**Comment by thorstenhater** [comment]
Translation has been fixed in 0.7. Also observe the 'reset' button in the r-click menu on the render view.
