### ISSUE TITLE
GUI crashes "Unknown locset" loading ACC

### ISSUE THREAD

**Issue by schmitts** [arbor-sim/gui#6]
Loading the attached `acc` file crashes with:

```
[2021-09-14 11:11:08.981] [error] Unknown locset
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unknown locset
[1]    152076 abort (core dumped)  ~/Downloads/Arbor_GUI-x86_64.AppImage
```

![image](https://user-images.githubusercontent.com/1502412/133230276-e3d05f2d-a6f7-4525-9748-d1fe19689fc8.png)

**Comment by thorstenhater** [comment]
Hi, thanks for reporting. Please provide the problematic file. (I assume something went wrong in your md above.)

**Comment by schmitts** [comment]
[foo.acc.gz](https://github.com/arbor-sim/gui/files/7160959/foo.acc.gz)

**Comment by schmitts** [comment]
> Hi, thanks for reporting. Please provide the problematic file. (I assume something went wrong in your md above.)

Sorry. File is uploaded.

**Comment by thorstenhater** [comment]
Hey,

I just (!) tried the file, ACC has changed substantially since then and it does not load anymore. 
From a quick scan of the file: The GUI's acc reader does not deal with inline locset definitions,
eg
```
(place (terminal) ...)
```
and instead expects
```
(label-dict (locset 'term' (terminal)))
...
(place 'term' ...)
```

**Comment by thorstenhater** [comment]
I added a corresponding error, which is part of the 0.7 milestone.
