### ISSUE TITLE
GUI crashes reading mech/g=v format

### ISSUE THREAD

**Issue by schmitts** [arbor-sim/gui#8]
Loading

[stick.acc.gz](https://github.com/arbor-sim/gui/files/7259253/stick.acc.gz)

crashes without error messages.

Explanation by @thorstenhater in chat:

>  ACC does not say which catalogues to use, so I have to manage that in the GUI myself.
> Therefore, mechanisms are written "catalogue::mechanism", thus need to use default::pas
> The globals are converted to but not from the mech/g=v format; that's a bug

**Comment by thorstenhater** [comment]
I added a much more robust parser and proper errors, should be gone in 0.7
